### ISSUE TITLE
Resizing the Modal panel

### ISSUE THREAD

**Issue by xu-chris** [ian-cox/Kirby-Structure-Tabs#1]
First: great plugin! After I've played a bit I think this has great potential to be the next big Kirby plugin ;-)

In the end my modal dialog looks like this:
![bildschirmfoto 2015-07-01 um 21 58 42](https://cloud.githubusercontent.com/assets/980778/8463684/b01fe8fe-203c-11e5-9692-766d2d5e6acc.png)

I think the modal dialog should resize to the size of it's content.

**Comment by ian-cox** [comment]
Oh, interesting. I haven't pressure tested the plugin yet and it looks like there are some issues when it has a lot of content. I'll have to look into this. Thanks!

**Comment by xu-chris** [comment]
Look to issue #2. There's the blueprint snippet (yes, it's long!)

**Comment by ian-cox** [comment]
Thats very strange, I don't remember it doing that when I was working on it this weekend. I just did a fresh install of plainkit and loaded it up and it's definitely an issue.

Would you rather it did something like this?

I'd prefer that the tab's didn't jump around but it might be better than full screen.

![modal-content](https://cloud.githubusercontent.com/assets/4325127/8465189/fe37b052-2015-11e5-9240-25aa091bf2d3.gif)

There is a new CSS class on the modal that I don't remember being there:   ( .modal-content-fixed )

If I disable it in the web inspector, I get what you see in the gif above.

**Comment by ian-cox** [comment]
I'm going to push the changes, let me know what you think.

Thanks!

**Comment by xu-chris** [comment]
Yeah, I think this is better than before - even when it's a bit difficult because the visual position on the screen of the tabs is changing on different sizes. But I'm not sure if this is really an UX problem. The relative position remains the same so in case of the UI it's consistent.

I'll try that out in a Guerilla UX Test ;-)
